/**
 * @File Name          : AnimalLocatorMock.cls
 * @Description        : 
 * @Author             : codeme.jai@gmail.com
 * @Group              : 
 * @Last Modified By   : codeme.jai@gmail.com
 * @Last Modified On   : 8/3/2019, 4:45:19 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    8/3/2019, 4:45:19 PM   codeme.jai@gmail.com     Initial Version
**/
gloabl class AnimalLocatorMock {

}