/**
 * @File Name          : IWGActions.cls
 * @Description        : 
 * @Author             : codeme.jai@gmail.com
 * @Group              : 
 * @Last Modified By   : codeme.jai@gmail.com
 * @Last Modified On   : 14/3/2019, 3:32:22 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    14/3/2019, 3:32:22 PM   codeme.jai@gmail.com     Initial Version
**/
global with sharing class IWGActions {

}