/**
 * @File Name          : RestSampleForInvoice.cls
 * @Description        : 
 * @Author             : codeme.jai@gmail.com
 * @Group              : 
 * @Last Modified By   : codeme.jai@gmail.com
 * @Last Modified On   : 14/3/2019, 11:08:49 AM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    14/3/2019, 11:08:49 AM   codeme.jai@gmail.com     Initial Version
**/
public with sharing class RestSampleForInvoice {
    
}