/**
 * @File Name          : WritingSoqlQueries.cls
 * @Description        : 
 * @Author             : codeme.jai@gmail.com
 * @Group              : 
 * @Last Modified By   : codeme.jai@gmail.com
 * @Last Modified On   : 2/4/2019, 3:21:10 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2/1/2019, 12:12:10 PM   codeme.jai@gmail.com     Initial Version
**/
public with sharing class WritingSoqlQueries {
    // Salesforce Object Query Language
    // Account [] accts = [Select Name, Phone, From Account];

    // Basic Syntax
    // SELECT fields FROM ObjectName [WHERE Condition]

        
}